import { IPlatform, resolve } from '@aurelia/kernel';
import { HttpClient } from '../http-client';
import { IFetchInterceptor } from '../interfaces';
import { ErrorNames, createMappedError } from '../errors';

/**
 * The strategy to use when retrying requests.
 */
export const RetryStrategy = /*@__PURE__*/Object.freeze({
  fixed: 0,
  incremental: 1,
  exponential: 2,
  random: 3
});

const defaultRetryConfig: IRetryConfiguration = {
  maxRetries: 3,
  interval: 1000,
  strategy: RetryStrategy.fixed
};

// fetch normalizes method names to upper case; TRACE is forbidden and POST/PATCH are not idempotent
const idempotentMethods = ['GET', 'HEAD', 'OPTIONS', 'PUT', 'DELETE'];

/**
 * Interceptor that retries requests on error, based on a given RetryConfiguration.
 */
export class RetryInterceptor implements IFetchInterceptor {
  /** @internal */
  private readonly p = resolve(IPlatform);
  public retryConfig: IRetryConfiguration;

  /**
   * Creates an instance of RetryInterceptor.
   */
  public constructor(retryConfig?: IRetryConfiguration) {
    this.retryConfig = {...defaultRetryConfig, ...(retryConfig ?? {})};

    if (this.retryConfig.strategy === RetryStrategy.exponential
      && (this.retryConfig.interval as number) <= 1000) {
      throw createMappedError(ErrorNames.retry_interceptor_invalid_exponential_interval, this.retryConfig.interval);
    }
  }

  /**
   * Called with the request before it is sent. It remembers the request so it can be retried on error.
   *
   * @param request - The request to be sent.
   * @returns The existing request, a new request or a response; or a Promise for any of these.
   */
  public request(request: IRetryableRequest): IRetryableRequest {
    if (!request.retryConfig) {
      request.retryConfig = {...this.retryConfig};
      request.retryConfig.counter = 0;
    }

    // do this on every request
    request.retryConfig.requestClone = request.clone();

    return request;
  }

  /**
   * Called with the response after it is received. Clears the remembered request, as it was succesfull.
   *
   * @param response - The response.
   * @returns The response; or a Promise for one.
   */
  public response(response: Response, request: IRetryableRequest): Response {
    // retry was successful, so clean up after ourselves
    delete request.retryConfig;
    return response;
  }

  /**
   * Handles fetch errors and errors generated by previous interceptors. This
   * function acts as a Promise rejection handler. It wil retry the remembered request based on the
   * configured RetryConfiguration.
   *
   * @param error - The rejection value from the fetch request or from a
   * previous interceptor.
   * @returns The response of the retry; or a Promise for one.
   */
  public responseError(error: unknown, request: IRetryableRequest, httpClient: HttpClient): Response | Promise<Response> {
    const retryConfig = request.retryConfig as Required<IRetryConfiguration> | undefined;
    // nothing to retry when the request never passed through this interceptor's request hook,
    // e.g. an earlier interceptor short-circuited with a response
    if (retryConfig == null) {
      throw error;
    }
    const { requestClone } = retryConfig;
    const signal = request.signal as AbortSignal | undefined;
    return Promise.resolve().then(() => {
      // aborted requests are never retried, and doRetry is not consulted for them
      if (retryConfig.counter >= retryConfig.maxRetries
        || signal?.aborted === true
        || (error as { name?: unknown } | null)?.name === 'AbortError') {
        delete request.retryConfig;
        throw error;
      }

      // without a doRetry callback only idempotent methods are retried, since the server may
      // already have applied non-idempotent ones
      const result = retryConfig.doRetry != null
        ? retryConfig.doRetry(error as Response, request)
        : idempotentMethods.includes(request.method);

      return Promise.resolve(result).then(doRetry => {
        if (doRetry) {
          retryConfig.counter++;
          const delay = calculateDelay(retryConfig);
          let newRequest: IRetryableRequest;
          return new Promise<void>((resolve, reject) => {
            if (signal == null) {
              this.p.setTimeout(resolve, !isNaN(delay) ? delay : 0);
              return;
            }
            // settle as soon as the caller aborts instead of holding the call open until the delay elapses
            const onAbort = () => {
              this.p.clearTimeout(timer);
              delete request.retryConfig;
              reject(abortReason(signal));
            };
            const timer = this.p.setTimeout(() => {
              signal.removeEventListener('abort', onAbort);
              resolve();
            }, !isNaN(delay) ? delay : 0);
            signal.addEventListener('abort', onAbort, { once: true });
          })
            .then(() => {
              newRequest = requestClone.clone() as IRetryableRequest;
              // attach before beforeRetry so user code can read the retry state
              newRequest.retryConfig = retryConfig;
              return retryConfig.beforeRetry?.(newRequest, httpClient) ?? newRequest;
            })
            .then(retryRequest => {
              delete request.retryConfig;
              // the caller may have aborted while an async beforeRetry was pending
              if (signal?.aborted === true) {
                throw abortReason(signal);
              }
              // a replacement built from a url (new Request(request.url, ...)) drops the caller's signal,
              // so rebuild it on that signal or a later abort would no longer reach the retry
              if (signal != null && retryRequest !== newRequest) {
                retryRequest = new Request(retryRequest, { signal });
              }
              // beforeRetry may return a brand-new Request; the config must live on a real
              // Request - a spread would produce a plain object that buildRequest treats as a url
              (retryRequest as IRetryableRequest).retryConfig = retryConfig;
              return httpClient.fetch(retryRequest);
            });
        }

        // no more retries, so clean up
        delete request.retryConfig;
        throw error;
      });
    });
  }
}

// fetch rejects with the signal's reason, which is not always an AbortError (custom reasons, AbortSignal.timeout)
function abortReason(signal: AbortSignal): unknown {
  return signal.reason ?? new DOMException('The operation was aborted.', 'AbortError');
}

function calculateDelay(retryConfig: IRetryConfiguration): number {
  const { interval, strategy, minRandomInterval, maxRandomInterval, counter } = retryConfig as Required<IRetryConfiguration>;

  if (typeof (strategy) === 'function') {
    return (retryConfig.strategy as (retryCount: number) => number)(counter);
  }

  switch (strategy) {
    case (RetryStrategy.fixed):
      return retryStrategies[RetryStrategy.fixed](interval);
    case (RetryStrategy.incremental):
      return retryStrategies[RetryStrategy.incremental](counter, interval);
    case (RetryStrategy.exponential):
      return retryStrategies[RetryStrategy.exponential](counter, interval);
    case (RetryStrategy.random):
      return retryStrategies[RetryStrategy.random](counter, interval, minRandomInterval, maxRandomInterval);
    default:
      throw createMappedError(ErrorNames.retry_interceptor_invalid_strategy, strategy);
  }
}

const retryStrategies = [
  // fixed
  interval => interval,

  // incremental
  (retryCount, interval) => interval * retryCount,

  // exponential
  (retryCount, interval) => retryCount === 1 ? interval : interval ** retryCount / 1000,

  // random
  (retryCount, interval, minRandomInterval = 0, maxRandomInterval = 60000) => {
    return Math.random() * (maxRandomInterval - minRandomInterval) + minRandomInterval;
  }
] as [
  (interval: number) => number,
  (retryCount: number, interval: number) => number,
  (retryCount: number, interval: number) => number,
  (retryCount: number, interval: number, minRandomInterval?: number, maxRandomInterval?: number) => number
];

export type IRetryableRequest = Request & { retryConfig?: IRetryConfiguration };

export interface IRetryConfiguration {
  maxRetries: number;
  interval?: number;
  strategy?: number | ((retryCount: number) => number);
  minRandomInterval?: number;
  maxRandomInterval?: number;
  counter?: number;
  requestClone?: Request;
  /** When omitted, only idempotent methods (GET, HEAD, OPTIONS, PUT, DELETE) are retried; aborted requests are never retried. */
  doRetry?(response: Response, request: Request): boolean | Promise<boolean>;
  beforeRetry?(request: Request, client: HttpClient): Request | Promise<Request>;
}

