version: "2" #required to adjust maintainability checks
checks:
# Argument count
# Methods or functions defined with a high number of arguments
  argument-count:
    enabled: false
# Complex logic
# Boolean logic that may be hard to understand
  complex-logic:
    enabled: false
# File length
# Excessive lines of code within a single file
  file-lines:
    enabled: false
# Identical blocks of code
# Duplicate code which is syntactically identical (but may be formatted differently)
  identical-code:
    enabled: false
# Method complexity (= cognitive complexity)
# Functions or methods that may be hard to understand
  method-complexity:
    enabled: false
# Method count
# Classes defined with a high number of functions or methods
  method-count:
    enabled: false
# Method length
# Excessive lines of code within a single function or method
  method-lines:
    enabled: false
# Nested control flow
# Deeply nested control structures like if or case
  nested-control-flow:
    enabled: false
# Return statements
# Functions or methods with a high number of return statements
  return-statements:
    enabled: false
# Similar blocks of code
# Duplicate code which is not identical but shares the same structure (e.g. variable names may differ)
  similar-code:
    enabled: false # default true
plugins:
  tslint:
    enabled: false
exclude_patterns:
# Exclude code that is not actually built and published
# The reasoning being that dev code like tests or build scripts can be changed without having to account for backwards compatibility and thus is much easier to refactor / tidy up at a later point in time
- ".circleci/"
- ".vscode/"
- "docs/"
- "**/__e2e__"
- "**/__tests__"
- "**/node_modules/"
- "**/dist/"
- "**/coverage/"
- "**/test/"
- "**/examples/"
- "/scripts/"
