export {
  BindingMode,
} from './binding-mode';

export {
  type StringBindingMode,
  type IAttributeComponentDefinition,
  type ICompiledElementComponentDefinition,
  type IComponentBindablePropDefinition,
  type IElementComponentDefinition,
  type ProcessContentHook,
  type IDomPlatform,
  ITemplateCompiler,
} from './interfaces-template-compiler';

export {
  IAttrMapper,
  type IsTwoWayPredicate
} from './attribute-mapper';

export {
  type AttributePatternDefinition,
  type AttributePatternKind,
  IAttributePattern,
  IAttributeParser,
  AttributeParser,
  ISyntaxInterpreter,
  SyntaxInterpreter,
  AttrSyntax,
  AttributePattern,
  Interpretation,
  ColonPrefixedBindAttributePattern,
  AtPrefixedTriggerAttributePattern,
  DotSeparatedAttributePattern,
  EventAttributePattern,
  RefAttributePattern,
  attributePattern,
} from './attribute-pattern';

export {
  type PartialBindingCommandDefinition,
  type BindingCommandDecorator,
  BindingCommandDefinition,
  type BindingCommandInstance,
  type BindingCommandStaticAuDefinition,
  type BindingCommandKind,
  type IBindableCommandInfo,
  type ICommandBuildInfo,
  type IPlainAttrCommandInfo,
  BindingCommand,
  AttrBindingCommand,
  type BindingCommandType,
  CaptureBindingCommand,
  ClassBindingCommand,
  DefaultBindingCommand,
  ForBindingCommand,
  FromViewBindingCommand,
  OneTimeBindingCommand,
  RefBindingCommand,
  SpreadValueBindingCommand,
  StyleBindingCommand,
  ToViewBindingCommand,
  TriggerBindingCommand,
  TwoWayBindingCommand,
  bindingCommand,
} from './binding-command';

export {
  IResourceResolver,
  IBindingCommandResolver,
  type IElementBindablesInfo,
  type IAttributeBindablesInfo,
  ITemplateCompilerHooks,
  TemplateCompiler,
  TemplateCompilerHooks,
  templateCompilerHooks,
  generateElementName,
} from './template-compiler';

export {
  ITemplateElementFactory,
} from './template-element-factory';

export {
  type AttributeBindingInstruction,
  type HydrateAttributeInstruction,
  type HydrateElementInstruction,
  type HydrateLetElementInstruction,
  type HydrateTemplateController,
  IInstruction,
  type Instruction,
  type InterpolationInstruction,
  type IteratorBindingInstruction,
  type LetBindingInstruction,
  type ListenerBindingInstruction,
  type MultiAttrInstruction,
  type PropertyBindingInstruction,
  type RefBindingInstruction,
  type SetAttributeInstruction,
  type SetClassAttributeInstruction,
  type SetPropertyInstruction,
  type SetStyleAttributeInstruction,
  type SpreadTransferedBindingInstruction,
  type SpreadElementPropBindingInstruction,
  type SpreadValueBindingInstruction,
  type StylePropertyBindingInstruction,
  type TextBindingInstruction,
  isInstruction,
  // Type constants (it = instruction type)
  itHydrateElement,
  itHydrateAttribute,
  itHydrateTemplateController,
  itHydrateLetElement,
  itSetProperty,
  itInterpolation,
  itPropertyBinding,
  itLetBinding,
  itRefBinding,
  itIteratorBinding,
  itMultiAttr,
  itTextBinding,
  itListenerBinding,
  itAttributeBinding,
  itStylePropertyBinding,
  itSetAttribute,
  itSetClassAttribute,
  itSetStyleAttribute,
  itSpreadTransferedBinding,
  itSpreadElementProp,
  itSpreadValueBinding,
} from './instructions';
