name: Trigger pr_full on request

on:
  # Allow maintainers to trigger by typing "/ci full" on a PR
  issue_comment:
    types: [created]
  # Allow maintainers to trigger by adding a label to the PR
  pull_request_target:
    types: [labeled]

permissions:
  contents: read

jobs:
  # Run when:
  #  A) A new comment was added on a PR AND it contains "/ci full" AND the commenter is a trusted association
  #  OR
  #  B) A label "ci:full" was added to the PR
  trigger:
    if: >
      (github.event_name == 'issue_comment' &&
       github.event.issue.pull_request &&
       contains(github.event.comment.body, '/ci full') &&
       (github.event.comment.author_association == 'MEMBER' ||
        github.event.comment.author_association == 'OWNER' ||
        github.event.comment.author_association == 'COLLABORATOR')) ||
      (github.event_name == 'pull_request_target' &&
       github.event.action == 'labeled' &&
       github.event.label.name == 'ci:full')
    runs-on: ubuntu-latest
    steps:
      - name: Resolve PR head ref
        id: head
        uses: actions/github-script@v7
        with:
          script: |
            const prNum = context.payload.pull_request?.number || context.issue.number;
            const { data: pr } = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: prNum
            });
            core.setOutput('branch', pr.head.ref);

      - name: Trigger CircleCI pipeline (pr_full)
        env:
          CIRCLECI_TOKEN: ${{ secrets.CIRCLECI_TOKEN }}
          BRANCH: ${{ steps.head.outputs.branch }}
        run: |
          curl -sS -X POST "https://circleci.com/api/v2/project/gh/${GITHUB_REPOSITORY}/pipeline" \
            -H "Circle-Token: ${CIRCLECI_TOKEN}" \
            -H "Content-Type: application/json" \
            -d "{\"branch\":\"${BRANCH}\",\"parameters\":{\"run_pr_full\":true}}"
